esphome:
  name: daikin-air-sensor
  project:
    name: "DAIKIN.BRY88AB151K"
    version: "PM2105" #根据自己PM2.5传感器型号选择，方便后续OTA查找文件
    # version: "PM2005"
  name_add_mac_suffix: true
  includes:
    - "cm1106.h"
    - "pm2105.h"  #拆机根据自己PM2.5传感器型号选择对应的文件
    # - "pm2005.h"

esp32:
  board: nodemcu-32s

wifi: #填写自己的WiFi及密码
  ssid: 'L'
  password: '1234567890'
  ap:
    ssid: "DAIKIN Fallback Hotspot"

captive_portal:

api:

ota:

web_server:
  port: 80

logger:

# bluetooth_proxy:  #需要蓝牙代理功能可以打开
#   active: true

# esp32_ble_tracker:

uart:
- id: cm1106_uart
  rx_pin: 16
  tx_pin: 17
  baud_rate: 9600
# - id: expand_uart  #侧面USB串口，连接其他传感器时可以打开，无法驱动可以调换RXTX顺序
#   tx_pin: 5
#   rx_pin: 18
#   baud_rate: 9600

i2c:
- id: pm25_bus
  sda: 23
  scl: 22
  scan: true
- id: th_bus
  sda: 19
  scl: 21
  scan: true

sensor:
- platform: custom
  lambda: |-
    auto cm1106Sensor = new CM1106Sensor(id(cm1106_uart), 10000);
    App.register_component(cm1106Sensor);
    return {cm1106Sensor};
  sensors:
  - name: "DAIKIN CO2 Sensor"
    id: co2sensor
    accuracy_decimals: 0
    unit_of_measurement: "ppm"
    device_class: carbon_dioxide
    on_value_range:
      - below: 1000       
        then:
          - switch.turn_off: co2led
      - above: 1000
        then:
          - switch.turn_on: co2led
- platform: custom
  lambda: |-
    auto pm25 = new pm2005();
    App.register_component(pm25);
    return {pm25};
  sensors:
  - name: "DAIKIN PM2.5 Sensor"
    unit_of_measurement: μg/m³
    accuracy_decimals: 0
    device_class: pm25
    on_value_range:
      - below: 50       
        then:
          - switch.turn_off: pm25led
      - above: 50
        then:
          - switch.turn_on: pm25led
- platform: sgp30
  i2c_id: th_bus
  eco2:
    name: "DAIKIN eCO2 Sensor"
    internal: true
  tvoc:
    name: "DAIKIN TVOC Sensor"
    device_class: volatile_organic_compounds
    unit_of_measurement: μg/m³
    accuracy_decimals: 0
    filters:
      - multiply: 4 #系数在3-4.5之间
      - median:
          window_size: 7
          send_every: 10
      - lambda: |-
          if (x > 10000) {
            return 10000;
          } else {
          return x;
          }
    on_value_range:
      - below: 3000       
        then:
          - switch.turn_off: tvocled
      - above: 3000
        then:
          - switch.turn_on: tvocled
  compensation:
    temperature_source: temperature
    humidity_source: humidity
  store_baseline: yes
  address: 0x58
  update_interval: 1s
- platform: hdc1080
  i2c_id: th_bus
  temperature:
    name: "DAIKIN Temperature Sensor"
    filters:
      - offset: -6.0
    id: temperature
  humidity:
    name: "DAIKIN Humidity Sensor"
    filters:
      - offset: 10.0
    id: humidity
  update_interval: 10s
- platform: wifi_signal
  name: "DAIKIN Signal"

switch:
- platform: custom
  lambda: |-
    auto cm1106Calib = new CM1106CalibrateSwitch(id(cm1106_uart));
    App.register_component(cm1106Calib);
    return {cm1106Calib};
  switches:
  - id: calibration
    internal: true
- platform: gpio
  pin: 4
  id: co2led
  icon: mdi:led-off
  name: "DAIKIN CO2 LED"
- platform: gpio
  pin: 32
  id: tvocled
  icon: mdi:led-off
  name: "DAIKIN TVOC LED"
- platform: gpio
  pin: 33
  id: pm25led
  icon: mdi:led-off
  name: "DAIKIN PM2.5 LED"

status_led:
  pin: 25

button:
- platform: restart
  name: "DAIKIN Restart"
- platform: template
  name: "DAIKIN CO2 Calibration" #按下后会将当前环境CO2浓度设置为基准400ppm，按下时请确保放入室外或此时CO2浓度足够低
  on_press:
    then:
      - switch.turn_on: calibration

binary_sensor:
- platform: template
  internal: true
  id: co2_calibration #CO2持续400ppm并保持5分钟会自动校准
  lambda: |-
    if (id(co2sensor).state == 400) {
      return true;
    } else {
      return false;
    }
  filters:
    - delayed_on: 5min
  on_press:
    then:
      - switch.turn_on: calibration
# - platform: gpio
#   pin: GPIO34
#   id: RESET
#   internal: true
#   on_press:  #按下背面RESET按钮后CO2指示灯亮，5分钟后将当前环境CO2浓度设置为基准400ppm并关闭CO2指示灯
#     then:
#       - switch.turn_on: co2led
#       - delay: 5min #可自定义修改时间
#       - switch.turn_on: calibration
#       - delay: 10s
#       - switch.turn_off: co2led
